### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by sfxcustoms** [baguscodestudio/bcs_questionare#1]
Cancel Button does not work for some reason

**Comment by baguscodestudio** [comment]
Fixed in the latest commit c4fbbcc822e393bdd3e1f8af782da969ee8e15ba

**Comment by sfxcustoms** [comment]
@baguscodestudio Cancel button works, but still the cursor remains there and you need to press scape to exit the cursor

**Comment by sfxcustoms** [comment]
![image](https://user-images.githubusercontent.com/77953089/150295088-c613fd1a-fd54-47bc-9eb9-a4f32d885575.png)

**Comment by baguscodestudio** [comment]
@sfxcustoms Whoops my bad, added another fix b2732c4cc9527993d607382e523e83229e48d068
