### ISSUE TITLE
Close Button

### ISSUE THREAD

**Issue by sfxcustoms** [baguscodestudio/bcs_questionare#2]
The button now can be closed but the cursor remains there, you need to keep pressing ESC for the cursor to hide

How To Reproduce:
1. Open Questionare
2. Press Exit
3. Check the cursor

**Comment by baguscodestudio** [comment]
What do you mean close button? I believe there is no close button? Only cancel tho? and have you tried the latest one?

**Comment by sfxcustoms** [comment]
sorry for late reply, its working fine now on your latest commit

**Comment by sfxcustoms** [comment]
thanks :>
